name: papy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0

  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.0  #^1.1.7
  json_annotation: ^4.4.0
  provider: ^6.0.2
  get: ^4.6.1
  google_fonts: ^2.3.1
  zefyrka: ^1.0.4+1
  flutter_colorpicker: ^1.0.3
  photo_manager: ^2.0.7
  video_player: ^2.3.0
  camera: ^0.9.4+18
  font_awesome_flutter: ^10.0.0
  flutter_share: ^2.0.0
  flutter_staggered_grid_view: ^0.4.1
  permission_handler: ^9.2.0
  image: ^3.1.3
  image_picker: ^0.8.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.4.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.5

  flutter_lints: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/papyrus.png"

flutter:
  assets:
    - assets/
    - i18n/ko.json
    - i18n/en.json
    - i18n/es.json
    - i18n/fr.json
    - i18n/de.json
    - i18n/it.json
    - i18n/ja.json
    - i18n/zh.json

  uses-material-design: true
