--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.7
--  \   \         Application : xaw2vhdl
--  /   /         Filename : ClockGenerator.vhd
-- /___/   /\     Timestamp : 05/08/2018 20:13:43
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st D:\Vhdlsx\Port\code\lib\.\ClockGenerator.xaw D:\Vhdlsx\Port\code\lib\.\ClockGenerator
--Design Name: ClockGenerator
--Device: xc3s400-5pq208
--
-- Module ClockGenerator
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- Period Jitter (unit interval) for block DCM_INST1 = 0.11 UI
-- Period Jitter (Peak-to-Peak) for block DCM_INST1 = 0.75 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity ClockGenerator is
   port ( U1_CLKIN_IN        : in    std_logic; 
          U1_RST_IN          : in    std_logic; 
          U1_U2_SELECT_IN    : in    std_logic; 
          U2_CLKIN_IN        : in    std_logic; 
          U2_RST_IN          : in    std_logic; 
          CLKFX_OUT          : out   std_logic; 
          U1_CLKIN_IBUFG_OUT : out   std_logic; 
          U1_CLK0_OUT        : out   std_logic; 
          U1_U2_CLK_OUT      : out   std_logic; 
          U2_CLKIN_IBUFG_OUT : out   std_logic; 
          U2_CLK0_OUT        : out   std_logic; 
          U2_LOCKED_OUT      : out   std_logic);
end ClockGenerator;

architecture BEHAVIORAL of ClockGenerator is
   signal GND_BIT            : std_logic;
   signal U1_CLKFB_IN        : std_logic;
   signal U1_CLKFX_BUF       : std_logic;
   signal U1_CLKIN_IBUFG     : std_logic;
   signal U1_CLK0_BUF        : std_logic;
   signal U2_CLKFB_IN        : std_logic;
   signal U2_CLKIN_IBUFG     : std_logic;
   signal U2_CLK0_BUF        : std_logic;
begin
   GND_BIT <= '0';
   U1_CLKIN_IBUFG_OUT <= U1_CLKIN_IBUFG;
   U1_CLK0_OUT <= U1_CLKFB_IN;
   U2_CLKIN_IBUFG_OUT <= U2_CLKIN_IBUFG;
   U2_CLK0_OUT <= U2_CLKFB_IN;
   BUFGMUX_INST : BUFGMUX
      port map (I0=>U1_CLK0_BUF,
                I1=>U2_CLK0_BUF,
                S=>U1_U2_SELECT_IN,
                O=>U1_U2_CLK_OUT);
   
   DCM_INST1 : DCM
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 8,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 54.253,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"8080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>U1_CLKFB_IN,
                CLKIN=>U1_CLKIN_IBUFG,
                DSSEN=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>U1_RST_IN,
                CLKDV=>open,
                CLKFX=>U1_CLKFX_BUF,
                CLKFX180=>open,
                CLK0=>U1_CLK0_BUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>open,
                PSDONE=>open,
                STATUS=>open);
   
   DCM_INST2 : DCM
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 54.253,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => FALSE,
            FACTORY_JF => x"8080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>U2_CLKFB_IN,
                CLKIN=>U2_CLKIN_IBUFG,
                DSSEN=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>U2_RST_IN,
                CLKDV=>open,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>U2_CLK0_BUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>U2_LOCKED_OUT,
                PSDONE=>open,
                STATUS=>open);
   
   U1_CLKFX_BUFG_INST : BUFG
      port map (I=>U1_CLKFX_BUF,
                O=>CLKFX_OUT);
   
   U1_CLKIN_IBUFG_INST : IBUFG
      port map (I=>U1_CLKIN_IN,
                O=>U1_CLKIN_IBUFG);
   
   U1_CLK0_BUFG_INST : BUFG
      port map (I=>U1_CLK0_BUF,
                O=>U1_CLKFB_IN);
   
   U2_CLKIN_IBUFG_INST : IBUFG
      port map (I=>U2_CLKIN_IN,
                O=>U2_CLKIN_IBUFG);
   
   U2_CLK0_BUFG_INST : BUFG
      port map (I=>U2_CLK0_BUF,
                O=>U2_CLKFB_IN);
   
end BEHAVIORAL;


